project_id = "zddkczbsykwuppyviqro"

[functions.register-device]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.notification-scheduler]
verify_jwt = false

[functions.generate-food-image]
verify_jwt = false

[functions.generate-all-food-images]
verify_jwt = false

[functions.rename-food-images]
verify_jwt = false
